### PR TITLE
Feature/compat 9.2

### PR DESCRIPTION
**Pull request by trasher**
Opened for reference... Far to be finished right now.

### CODE REVIEW

**Comment by trasher** [comment]
Thanks for the review; but there still are issues; on importing operating systems for example :/

**Comment by PMarxen** [comment]
something new about this?

**Comment by prohand** [comment]
Hello,

Something new about this?

Thank you in advance

**Comment by trasher** [comment]
Until new commits are added on the current PR; nothing new, no.
I do not have time to work on this plugin right now; other may help if they want... :)

**Comment by PMarxen** [comment]
Currently I do not have time to work with the code, too.

**Comment by vollkommenIrrelevant** [comment]
@trasher 
do you have time to review?
- [https://github.com/pluginsGLPI/datainjection/pull/51/commits/c3a746db26bc41e9f27f712e11e19e899ab2448c](https://github.com/pluginsGLPI/datainjection/pull/51/commits/c3a746db26bc41e9f27f712e11e19e899ab2448c)
- [https://github.com/pluginsGLPI/datainjection/pull/50/commits/0469c1b10ba24d61deec8f74caa052ce5447cf65](https://github.com/pluginsGLPI/datainjection/pull/50/commits/0469c1b10ba24d61deec8f74caa052ce5447cf65)

thank you for attention

**Comment by Ph1eG** [comment]
402/5000
Hello and thank you in advance for all your work!
Several users of the datainjection plugin wish to update GLPI in version 9.2.1 (cf forum GLPI). Datainjection being used in a production environment, they can not update GLPI.
Would you know how soon this plugin will be reviewed to be compatible with version 9.2.1 of GLPI?

Thank you for your answers.
Ph1

**Pull request merged**
