### PR TITLE
File not found creating model fix #60

### LINKED ISSUE #60: File not found creating model
Bonjour,
Lors de la création d'un nouveau modèle, le chargement du fichier CSV génère l'erreur "fichier introuvable" 
GLPI 9.2.1 / DataInjection 2.5.0
cdlt

### PR DESCRIPTION
**Pull request by amma35**

### CODE REVIEW

**Comment by cedric-anne** [comment]
@amma35 

I cannot reproduce the problem on my installation which is running on a debian server. Was you able to reproduce this issue before your fix ?

Regards

**Comment by amma35** [comment]
Yes, I get the error well, the file path does not contain the"/".

**Comment by cedric-anne** [comment]
OK.

It is consistent with description in ticket. I will merge it.

Thanks

**Comment by cedric-anne** [comment]
Merged in develop branch. commit: https://github.com/pluginsGLPI/datainjection/commit/7a9fd947146fa1c858639e9cb4ee3e6542f94da9

**Comment by amma35** [comment]
Thanks

**Pull request closed without merging**
