### PR TITLE
Statecheck Integration

### PR DESCRIPTION
**Pull request by maunat**
Data Injection Plugin will be able to integrate itself with Statecheck Plugin.
For each CSV entry, rules defined with Statecheck Plugin will be triggered. All the entries not respecting these rules will be discarded. The resulting CSV will contain the note on which rules have been fired but not respected.

### CODE REVIEW

**Comment by maunat** [comment]
Good morning,

Thank you for your prompt reply.

I'd like to know more, if possible, about the roadmap behind this kind of
integration because I'm working on a *critical project*.
And if, GLPI will be provided with such a kind of checks during the massive
import after the implementation.

Awaiting your kind reply.
Thank you so much.

Best Regards,

Maurizio

Il giorno mar 10 ott 2023 alle ore 10:14 Adrien Clairembault <
***@***.***> ha scritto:

**Comment by AdrienClairembault** [comment]
There is no public roadmap regarding this plugin integration (yet).
I also can't comment on the exact list of features but I don't think this kind of checks are planned at this moment.

I am not familiar with the `StateCheck` plugin but from what I understand it does some additional checks before an item is added to the database through the `PRE_ITEM_ADD`  hook.

Unless I'm wrong it seems the `PluginDatainjectionCommonInjectionLib::effectiveAddOrUpdate()` method trigger `CommonDBTM::add()`, which should in turn already trigger the `PRE_ITEM_ADD` hook.

With that in mind, shouldn't the import already take the `StateCheck` plugin into account thanks to this hook ?

**Comment by maunat** [comment]
Thank you for your reply.

I'm wondering if you are suggesting to put the integration code in the Data Injection PRE_ITEM_ADD hook (not implemented or overrided by now) to be accepted instead of in the middle of the _processAddOrUpdate()_ method. In this case, I'll provide you such a kind of implementation.

But, as you said, with no clear evidence about your integration in the GLPI core, I'm not understanding why my pull request has been rejected.

Best regards,

**Comment by AdrienClairembault** [comment]
> Thank you for your reply.
> 
> I'm wondering if you are suggesting to put the integration code in the Data Injection PRE_ITEM_ADD hook (not implemented or overrided by now) to be accepted instead of in the middle of the _processAddOrUpdate()_ method. In this case, I'll provide you such a kind of implementation.

What I am trying to say is that GLPI's already have a `PRE_ITEM_ADD` hook that will be called anytime an item is being created (including item created through the `datainjection` plugin):

image

Don't you think that the `statecheck` plugin should be able to directly use this hook without any modification in `datainjection` ?

**Comment by maunat** [comment]
Hi,
It's true that GLPI provides hooks like PRE_ITEM_ADD but, as far I studied the product, it's even true that GLPI calls the PRE_ITEM_ADD, contextually, during the plugin flow/lifecycle so, an item added from the DataInjection Plugin will never call the PRE_ITEM_ADD of the StatecheckPlugin unless the DI Plugin itself calls the hook.

Moreover, what my implementation here (now, to be updated due to further implementation on my fork) aims to achieve is to validate the CSV inputs and to add as last column the notes from Statecheck plugin reporting all the rules fired but not respected.

Hope you agree with my vision, correct me if I'm wrong otherwise.
Thank you so much,

M

**Pull request closed without merging**
