### PR TITLE
fix(injection): global fix of CommonDBChild injection

### PR DESCRIPTION
**Pull request by stonebuzz**
global fix of CommonDBChild injection

### CODE REVIEW

**Comment by Mirkk** [comment]
Tested, works! Thanks

**Review by cedric-anne — APPROVED** [review]

**Comment by Mirkk** [comment]
Hi @cedric-anne @stonebuzz,
To make the import work also for item_operatingsystem (i.e. importing the computer OS), in the same place I added also "CommonDBRelation" beyond "CommonDBChild".
However, I did not get why there are all these conditions. Are there cases in which copying item_id and itemtype to $toinject leads to a problem?

**Comment by cedric-anne** [comment]
Hi @Mirkk 

Could you try to apply patch from #306 and do a global check to see if problem is solved ?

**Comment by Mirkk** [comment]
Thanks @cedric-anne , I'll try it in several imports today. However, these imports are quite specific and only with assets, no ITIL types.
In the last days I implemented also various fixes and additions to import virtualmachines, disks(volumes), softwareversions. I'll try to publish them when everything works well.

**Pull request merged**
